name: agitation
baseurl: /agitation
description: A Control Structure for Cancellation
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.2-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
